version: "3.9"
services:
  reviews-api:
    build:
      context: .
    image: reviews-api
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 3001:3001
  mongodb:
    image: mongo
    container_name: sdc-mongodb
    volumes:
      - /mongo/mongod.conf:/etc/mongod.conf
      - /mongo/data:/data/db
    command: ["mongod"]
    ports:
      - 27017:27017